### ISSUE TITLE
[Reproducing quantitative numbers of AOT and DeAOT]

### ISSUE THREAD

**Issue by Amshaker** [yoxu515/aot-benchmark#63]
Hi authors,

Thank you for sharing your awesome work!

I am trying to reproduce the paper numbers for the DAVIS 2017 val set. When I use your provided predictions, I can use the Davis toolkit to produce the exact numbers. 
  
  ```
F:
    decay: 0.10240888591209721
    mean: 0.863435248777786
    recall: 0.9270630649303405
  J:
    decay: 0.0762513037599667
    mean: 0.8075060232398165
    recall: 0.9024135557843277
 
```   
However, when I follow the eval.py script to generate the predictions using your provided checkpoints, the numbers are totally different. This script I am using is 
`python tools/eval.py --exp_name aotl  --stage pre_ytb_dav --model aotl --dataset davis2017 --split val --gpu_num 4`

The results are much less compared to the results of the provided predictions:

```
  F:
    decay: 0.4348152915537652
    mean: 0.5862216030374168
    recall: 0.6356685013535934
  J:
    decay: 0.3545346016158602
    mean: 0.5630311658597108
    recall: 0.6248207335387892
```

Could you please let me know what could be the reason for such gaps in the results?

I am looking forward to hearing back from you.

Best regards,
Abdelrahman.
